version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - "5434:5432"

  api:
    build:
      context: .
      target: builder
    image: editor-api:builder
    depends_on:
      - db
    volumes:
      - .:/app
      # This is here to avoid rails finding stale pid-files in tmp/pids and then
      # thinking it is already running:
      - type: tmpfs
        target: /app/tmp/pids
      # The cache should be on tmpfs too, to ensure it gets wiped between runs
      - type: tmpfs
        target: /app/tmp/cache
    command: bin/rails server --port 3009 --binding 0.0.0.0
    # NB: The API runs on port 3009.
    ports:
      - "3009:3009"
    stdin_open: true # For docker run --interactive, i.e. keep STDIN open even if not attached
    tty: true # For docker run --tty, i.e. allocate a pseudo-TTY. Important to allow interactive byebug sessions
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  smee:
    image: deltaprojects/smee-client
    command: -u $SMEE_TUNNEL -t http://api:3009/github_webhooks

networks:
  default:
    name: shared-development
