services:
  api:
    build:
      context: .
      target: dev-container
    command: bash bin/docker-debug-entrypoint.sh
    volumes:
      # - ${HOME}/.bashrc:/root/.bashrc:ro # Map a ~/.bashrc in your home directory for customising bash
      - ${HOME}/.ssh:/root/.ssh:ro # To share any ssh keys with the container
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle

volumes:
  node_modules: null
  postgres_data:
  bundle: null
