name: RaspberryPiFoundation/editor-api/code_quality
on:
  push:
    branches:
    - main
env:
  GITHUB_AUTH_TOKEN: xxxxf7C3
jobs:
  rubocop:
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2
    steps:
    - name: Set up bundler cache
      uses: ruby/setup-ruby@v1.144.0
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - uses: actions/checkout@v3.3.0
    - run: bundle check || bundle install
      env:
        BUNDLE_DEPLOYMENT: true
    - name: Inspecting with Rubocop
      run: bundle exec rubocop --format progress
